# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routes_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('Areas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Areas')),
            ],
        ),
    ]
