# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canyon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canyon_text', models.CharField(max_length=200)),
            ],
        ),
    ]
