# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Areas',
            new_name='Area',
        ),
        migrations.RenameModel(
            old_name='Routes',
            new_name='Route',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='Areas',
            new_name='Area',
        ),
    ]
