# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20170501_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='area',
            name='areas_text',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
