# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_auto_20170501_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='votes',
        ),
        migrations.AddField(
            model_name='area',
            name='location_text',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
