# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20170501_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='comments_text',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='location_text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='rating_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
