# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-01 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_auto_20170501_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area',
            new_name='areas_text',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='route_name',
            new_name='routes_text',
        ),
    ]
